### ISSUE TITLE
Media meta does not work in release mode in Android

### ISSUE THREAD

**Issue by vinay93** [vforvasile/rn-media-meta#2]
Getting the following exception in release mode.

E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.cte.wearables, PID: 22833
    java.lang.NoSuchFieldError: no "J" field "mNativeContext" in class "Lwseemann/media/FFmpegMediaMetadataRetriever;" or its superclasses
        at wseemann.media.FFmpegMediaMetadataRetriever.native_init(Native Method)
        at wseemann.media.FFmpegMediaMetadataRetriever.<clinit>(Unknown Source:43)
        at com.mybigday.rnmediameta.RNMediaMeta.getMetadata(Unknown Source:39)
        at com.mybigday.rnmediameta.RNMediaMeta.access$000(Unknown Source:0)
        at com.mybigday.rnmediameta.a.run(Unknown Source:8)

Is anyone facing the same issue?

**Comment by vforvasile** [comment]
@vinay93 can you share some example code you're using?

**Comment by MichaelDepp** [comment]
it is due to using proguard this can be fixed using
-keep class wseemann.media.**{ *; }
-keep class wseemann.media.FFmpegMediaMetadataRetriever {
*** mNativeContext;
}

in proguard-rules.pro file

**Comment by nareshravva** [comment]
> it is due to using proguard this can be fixed using -keep class wseemann.media.**{ *; } -keep class wseemann.media.FFmpegMediaMetadataRetriever { *** mNativeContext; }
> 
> in proguard-rules.pro file

Its working.
