### ISSUE TITLE
android setdatasource failed status = 0xffffffff

### ISSUE THREAD

**Issue by sekizlipenguen** [vforvasile/rn-media-meta#3]
I'm getting the following error I need your help!

setdatasource failed status = 0xffffffff

android log

10-07 13:16:21.958   864  2306 W System.err: java.lang.IllegalArgumentException: setDataSource failed: status = 0xFFFFFFFF
10-07 13:16:21.959   864  2306 W System.err: 	at wseemann.media.FFmpegMediaMetadataRetriever.setDataSource(Native Method)
10-07 13:16:21.959   864  2306 W System.err: 	at com.mybigday.rnmediameta.RNMediaMeta.getMetadata(RNMediaMeta.java:97)
10-07 13:16:21.959   864  2306 W System.err: 	at com.mybigday.rnmediameta.RNMediaMeta.access$000(RNMediaMeta.java:23)
10-07 13:16:21.959   864  2306 W System.err: 	at com.mybigday.rnmediameta.RNMediaMeta$1.run(RNMediaMeta.java:215)

**Comment by jyling** [comment]
I realised this is an old thread, well this will be useful for future people looking for a solution for this issue

i found out that the issue is because of the permission, try asking the permission first
